### ISSUE TITLE
Switch build pipeline to new Python library

### ISSUE THREAD

**Issue by mbollmann** [acl-org/acl-anthology#3996]
A while ago, we merged [the new Python library](https://github.com/acl-org/acl-anthology/tree/master/python) into this repo, but the build pipeline still [uses the legacy code](https://github.com/acl-org/acl-anthology/tree/master/bin/anthology).

Porting the build pipeline to the new library now happens on the https://github.com/acl-org/acl-anthology/tree/build-pipeline-with-new-library branch.

### Roadmap

- [X] Create `data/yaml/papers/*` files with new library
- [X] Create `data/yaml/volumes.yaml` with new library
- [X] Create `data/yaml/people/*` files with new library
- [X] Create `data/yaml/venues.yaml` with new library
- [X] Create `data/yaml/events.yaml` with new library
- [X] Create `data/yaml/sigs.yaml` with new library
- [x] Create BibTeX with new library
- [X] Inspect diffs of generated YAML files between old and new libraries for any functional changes
  - [X] Check `papers/*.yaml` for functional equivalence
    - Tons of diffs.; see diff script.
  - [X] Check `volumes.yaml` for functional equivalence
    - More events are listed than before. This seems more correct than before; e.g., [W99-09](https://aclanthology.org/volumes/W99-09/) does not list an event "ws-1999", even though there is [an XML file that explicitly defines and links it](https://github.com/acl-org/acl-anthology/blob/master/data/xml/1999.ws.xml). The new pipeline explicitly lists it as an event under W99-09, which seems more correct.
    - Some unused keys are removed.
    - The order in which SIGs are listed is now alphabetical, which differs from how it was before.
  - [X] Check `people/*.yaml` for functional equivalence
    - Lots of differences due to slight changes in name scoring, forcing the canonical name if set in `name_variants.yaml` in all cases, and more consistently adding name variants in different scripts to the displayed canonical name
  - [X] Check `venues.yaml` for functional equivalence
    - Sorting of volumes behaves slightly differently, but more consistently (volumes are always sorted alphabetically by their collection ID, but order within a collection – i.e. XML file – is preserved).
  - [X] Check `events.yaml` for functional equivalence
    - Sorting algorithm for associated volumes behaves slightly differently, but usually more correctly (Findings wasn't always moved above workshops before with joint events; main volumes of EMNLP 2018 were not moved to the top).
  - [X] Check `sigs.yaml` for functional equivalence
    - Years in keys are not being quoted; `url: null` is omitted.

**Custom diff script to help with this: https://gist.github.com/mbollmann/827a079023ebdd18b4d06c28566fac0d**

### Performance optimizations

- [X] Generating bibliography strings was so far done with citeproc-py. Replacing this with [a custom Python function](https://github.com/acl-org/acl-anthology/blob/c4239b41949f445f944c31c4b9854b34976d90a4/python/acl_anthology/utils/citation.py#L111) speeds up the generation of bibliography strings from _four minutes_ to _a few seconds_ in my local testing.
- #4153 (moved to separate issue now, since changing the data format complicates checking for functional equivalence)

**Comment by mbollmann** [comment]
Pending my checks for functional equivalence, the new library is much faster in generating all the Hugo data files:

```
on master [?]
~/r/acl-anthology/bin $ time python create_hugo_yaml.py -c

________________________________________________________
Executed in  175.53 secs    fish           external
   usr time  173.80 secs  290.00 micros  173.80 secs
   sys time    1.25 secs   76.00 micros    1.25 secs


on build-pipeline-with-new-library [?]
~/r/acl-anthology/bin $ time python create_hugo_yaml.py -c

________________________________________________________
Executed in   73.86 secs    fish           external
   usr time   74.15 secs    0.00 micros   74.15 secs
   sys time    1.67 secs  935.00 micros    1.67 secs
```

**Comment by mbollmann** [comment]
It's also successfully building already (although the BibTeX part is not ported yet):
https://preview.aclanthology.org/build-pipeline-with-new-library/

**Comment by mbollmann** [comment]
**Progress update:** I now checked `volumes.yaml` for functional equivalence. All these checks did already uncover various minor bugs and oddities.

Since a naive diff between files was getting too tedious, I [defined my own diff script](https://gist.github.com/mbollmann/827a079023ebdd18b4d06c28566fac0d) that specifically ignores certain expected differences. At the same, it serves as documentation for what those expected differences are.

The "big" files, namely the people and paper YAML files, are still left to do, but I hope I can finish this work before the end of the year.

**Comment by mjpost** [comment]
Following your comment from #4147, I agree it would be awesome to get this finished off. There have been at least a handful of changes to the original implementation and I fear the longer we let this sit the more we will diverge.

I wonder if we should adopt a sink-or-swim approach: we delete the original implementation, and then we are simply forced to update new scripts in a lazy fashion as we need them.

I have a few comments along that route:
* It would be helpful to create the PR so we could easily see and comment on the diff. I confess I don't really know what's changed in terms of the API.
* If you ported `create_hugo_yaml.py`, that would be a big help to me as a reference for porting `ingest.py` and `ingest_aclpub2.py`. The other important ones will be related to adding DOIs and handling corrections, but I don't anticipate these would be difficult
* I did install the pypi module and loaded it, and my first comment is that it would be really nice to address a weakness with the current module, which is that the import takes a long time. I wonder whether there is something we could do with lazy evaluation (ideally) or a timestamped cache that would help out with this

**Comment by mbollmann** [comment]
> Do you mean you experienced long import times with the _new_ module? That would be weird, as it’s entirely designed to only load information at the moment you need it,

Oh, but I should add that instantiating it without pointing it to an existing Anthology data directory will clone the Git repo, which will take some time of course. :)

**Comment by mjpost** [comment]
Regarding import times—the new module takes a few seconds to load on my MacBook Pro. This does seem odd but maybe is just my local machine. The load time of the module itself is quite fast.

**Comment by mbollmann** [comment]
> Regarding import times—the new module takes a few seconds to load on my MacBook Pro. This does seem odd but maybe is just my local machine. The load time of the module itself is quite fast.

I consistently get around 0.8s on my (not very beefy) ThinkPad. You could try

`python -X importtime -c "from acl_anthology import Anthology"`

and see what it outputs. (Looking at this actually gave me an idea how to cut a third of that...)
